# Generated by Django 3.0.4 on 2020-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_sharing', '0003_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
