# Generated by Django 3.0.4 on 2020-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_sharing', '0004_auto_20200327_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
